# Generated by Django 5.2.6 on 2025-10-27 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0002_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    ("followed", "Followed"),
                    ("commented", "Commented"),
                    ("mentioned", "Mentioned"),
                    ("retweeted", "Retweeted"),
                    ("liked", "Liked"),
                    ("welcome", "Welcome"),
                ],
                max_length=10,
            ),
        ),
    ]
