# Generated by Django 5.2.6 on 2025-10-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0003_alter_notification_sender_alter_notification_verb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    ("followed", "Followed"),
                    ("commented", "Commented"),
                    ("mentioned", "Mentioned"),
                    ("retweeted", "Retweeted"),
                    ("liked", "Liked"),
                    ("welcome", "Welcome"),
                    ("reset", "Reset"),
                    ("changed", "Changed"),
                ],
                max_length=10,
            ),
        ),
    ]
