# Generated by Django 5.2.6 on 2025-10-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("deactive", "Deactive"),
                    ("suspended", "Suspended"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
