# Generated by Django 5.2.6 on 2025-10-13 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0005_retweet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retweet",
            name="tweet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retweets",
                to="tweets.tweet",
            ),
        ),
    ]
