# Generated by Django 5.2.6 on 2025-11-12 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0007_alter_retweet_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="retweet",
            constraint=models.UniqueConstraint(
                fields=("user", "tweet"), name="unique_user_tweet_retweet"
            ),
        ),
    ]
